rootURL: https://dvc.org
fileIncludePatterns: '{.github,content,src}/**/*.{css,js,jsx,md,tsx,ts,json}'
fileExcludePatternFiles: config/link-check/excluded-files.yml
linkExcludePatternFiles: config/link-check/excluded-links.yml
bottlenecks:
  '*.wikipedia.org':
    minTime: 2000
    maxConcurrent: 1

  '*.github.com':
    minTime: 1000
    maxConcurrent: 1
