name: Link Check Deploy
on: deployment_status

jobs:
  run:
    name: Check
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:

    - uses: actions/checkout@v2

    - uses: LouisBrunner/checks-action@v0.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Check
        status: in_progress
        conclusion: neutral
        output: >-
          {"summary": "Running master diff Link Check on ${{ github.event.deployment.payload.web_url }}"}

    - name: Run the link check script
      id: check
      uses: "iterative/link-check.action@master"
      with:
        configFile: "config/link-check/config.yml"
        rootURL: "${{ github.event.deployment.payload.web_url }}"
        output: checkAction

    - uses: LouisBrunner/checks-action@v0.1.0
      if: ${{ success() }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Check
        status: completed
        conclusion: ${{ steps.check.outputs.conclusion }}
        output: ${{ steps.check.outputs.output }}

    - uses: LouisBrunner/checks-action@v0.1.0
      if: ${{ failure() }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Check
        status: completed
        conclusion: failure
        output: >-
          {"summary": "The Link Check script had an error!"}
