name: Link Check Deploy
on:
  - deployment
  - deployment_status

jobs:
  initialize:
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment'

    outputs:
      check_id: ${{ steps.check.outputs.check_id }}

    steps:
      - id: check
        uses: rogermparent/checks-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Link Check Deploy
          status: queued

  check:
    needs: initialize
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:
      - uses: actions/checkout@v2

      - uses: rogermparent/checks-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ needs.initialize.outputs.check_id }}
          status: in_progress
          output: >-
            {"summary": "Running master diff Link Check on ${{
            github.event.deployment.payload.web_url }}"}

      - name: Run Link Check
        id: check
        uses: 'iterative/link-check.action@master'
        with:
          configFile: 'config/link-check/config.yml'
          rootURL: '${{ github.event.deployment.payload.web_url }}'
          output: checksAction

      - uses: rogermparent/checks-action@master
        if: ${{ success() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ needs.initialize.outputs.check_id }}
          status: completed
          conclusion: ${{ steps.check.outputs.conclusion }}
          output: ${{ steps.check.outputs.output }}

      - uses: rogermparent/checks-action@master
        if: ${{ failure() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          check_id: ${{ needs.initialize.outputs.check_id }}
          status: completed
          conclusion: failure
          output: >-
            {"summary": "The Link Check script had an error!"}
