name: Link Check All
on:
  deployment:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    name: Link Check All
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Run Link Check
      uses: "iterative/link-check.action@master"
      with:
        source: "filesystem"
        configFile: "./config/link-check/config.json"
        reportUnusedPatterns: true
        output: >-
          ["consoleLog", "exitCode"]
