name: Link Check Deploy
on:
  - deployment
  - deployment_status

jobs:
  check:
    name: Link Check Deploy
    runs-on: ubuntu-latest
    if:
      github.event_name == 'deployment_status' &&
      github.event.deployment_status.state == 'success'

    steps:
      - uses: actions/checkout@v2

      - name: Run Link Check
        id: check
        uses: 'iterative/link-check.action@master'
        with:
          configFile: 'config/link-check/config.yml'
          rootURL: '${{ github.event.deployment.payload.web_url }}'
          output: >-
            ["consoleLog", "exitCode"]
