name: Link Check Deploy
on: deployment

jobs:
  run:
    name: Initialize
    runs-on: ubuntu-latest
    steps:
    - uses: LouisBrunner/checks-action@v0.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Check
        status: in_progress
        conclusion:
