name: Link Check Deploy
on: deployment

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: LouisBrunner/checks-action@v0.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Link Check Deploy
        status: in_progress
        conclusion: neutral
