name: Link Check All
on:
  deployment:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run:
    name: Link Check All Job
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Run the link check script
      uses: "iterative/link-check.action@v0.4"
      with:
        source: "filesystem"
        configFile: "./.linkcheckrc.json"
        reportUnusedPatterns: true
        output: >-
          ["consoleLog", "exitCode"]
