name: Link Check Deploy
on: deployment_status

jobs:
  init:
    name: Initialize Deploy Check
    runs-on: ubuntu-latest
    if: github.event.action == 'created'

    steps:

    - uses: rogermparent/checks-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Deploy Check
        status: queued

  check:
    name: Deploy Check
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'

    steps:

    - uses: actions/checkout@v2

    - uses: rogermparent/checks-action@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Deploy Check
        status: in_progress
        output: >-
          {"summary": "Running master diff Link Check on ${{ github.event.deployment.payload.web_url }}"}

    - name: Run the link check script
      id: check
      uses: "iterative/link-check.action@master"
      with:
        configFile: "config/link-check/config.yml"
        rootURL: "${{ github.event.deployment.payload.web_url }}"
        output: checksAction

    - uses: rogermparent/checks-action@master
      if: ${{ success() }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Deploy Check
        status: completed
        conclusion: ${{ steps.check.outputs.conclusion }}
        output: ${{ steps.check.outputs.output }}

    - uses: rogermparent/checks-action@master
      if: ${{ failure() }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Deploy Check
        status: completed
        conclusion: failure
        output: >-
          {"summary": "The Link Check script had an error!"}
